# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# 기본 언어 정의 (단일 언어: 한국어)
ko:
  languageCode: ko-kr
  # 다국어를 쓰지 않는 경우 contentDir는 기본값 사용
  #contentDir: content

# 참고) 영어를 추가해 2개 언어로 운영하려면 아래 예시를 참고해 추가하세요.
#en:
#  languageCode: en-us
#  contentDir: content/en  # 영어 컨텐츠는 content/en/ 에 위치
#  params:
#    description: Site description in English...
#  menu:
#    main:
#      - name: Home
#        url: '/'
#        weight: 10
