# 내비게이션(상단 메뉴) 설정
# - 홈 위젯으로 점프하려면 URL을 `/#파일명` 형태로 작성합니다.
#   예) `content/home/portfolio.md` → `/#portfolio`
# - `weight` 값이 작을수록 왼쪽(상단에서 먼저) 배치됩니다.

main:
  - name: Home
    url: /
    weight: 5
  - name: About
    identifier: about
    url: /about/
    weight: 10
  # About dropdown items
  - name: About · Summary
    url: /about/#summary
    parent: about
    weight: 11
  - name: About · Interests
    url: /about/#interests
    parent: about
    weight: 12
  - name: About · Skills
    url: /about/#skills
    parent: about
    weight: 13
  - name: About · Tech
    url: /about/#tech
    parent: about
    weight: 14
  - name: About · Education
    url: /about/#education_timeline
    parent: about
    weight: 15
  - name: About · Contact
    url: /about/#contact_map
    parent: about
    weight: 16
  - name: Project
    url: /project/
    weight: 20
  - name: Qualifications
    url: /qualifications/
    weight: 30
  - name: Award
    url: /award/
    weight: 40
  - name: Skills
    url: /skills/
    weight: 50
  - name: Experience
    url: /experience/
    weight: 60
