# 내비게이션(상단 메뉴) 설정
# - 홈 위젯으로 점프하려면 URL을 `/#파일명` 형태로 작성합니다.
#   예) `content/home/portfolio.md` → `/#portfolio`
# - `weight` 값이 작을수록 왼쪽(상단에서 먼저) 배치됩니다.

main:
  - name: Home
    pageRef: /
    weight: 5
  - name: About
    pageRef: about
    weight: 10
  - name: Project
    pageRef: project
    weight: 20
  - name: Qualifications
    pageRef: qualifications
    weight: 30
  - name: Award
    pageRef: award
    weight: 40
  - name: Skills
    pageRef: skills
    weight: 50
  - name: Experience
    pageRef: experience
    weight: 60
