# 내비게이션(상단 메뉴) 설정
# - 홈 위젯으로 점프하려면 URL을 `/#파일명` 형태로 작성합니다.
#   예) `content/home/portfolio.md` → `/#portfolio`
# - `weight` 값이 작을수록 왼쪽(상단에서 먼저) 배치됩니다.

main:
  - name: 홈
    url: /
    weight: 10
  - name: 소개
    url: about/
    weight: 20
  - name: 프로젝트
    url: /#portfolio
    weight: 30
