# 내비게이션(상단 메뉴) 설정
# - 홈 위젯으로 점프하려면 URL을 `/#파일명` 형태로 작성합니다.
#   예) `content/home/portfolio.md` → `/#portfolio`
# - `weight` 값이 작을수록 왼쪽(상단에서 먼저) 배치됩니다.

main:
  - name: About
    url: /about/
    weight: 10
  - name: Project
    url: /project/
    weight: 20
  - name: Qualifications
    url: /qualifications/
    weight: 30
  - name: Award
    url: /award/
    weight: 40
  - name: Skills
    url: /skills/
    weight: 50
  - name: Experience
    url: /experience/
    weight: 60
